### ISSUE TITLE
serial port and file setup

### ISSUE THREAD

**Issue by Gavsv8** [dimhoff/mt333x-fw-utils#1]
@dimhoff  Great work getting something together for this. This isn't an issue but I am unfamiliar with Python and am having trouble getting the firmware dump to execute. How do I specify my COM20 serial port and an output file.  I keep trying different things but keep getting:

mt333x_fw_dump.py: error: the following arguments are required: serial_port, output_file

**Comment by dimhoff** [comment]
All the tools are command line tools. Invoke it as follows from the command line(cmd.exe): mtk333x_fw_dump.py com20 output.dat

You can also use the '-h' option to get the full usage information.

**Comment by Gavsv8** [comment]
@dimhoff  thanks for your support. I can now run this with the different options from the command line. I've tried all different baud rates for -b and --nmea-baud, tried just dumping the header and also placed the gps in command mode manual in hyerterminal using $PMTK180*3B\r\n. I can send commands with hyperterminal and get the correct responses but when I try to get the firmware dump I keep getting the below response--

C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils>mt333x_fw_dump.py com20 output.dat
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils\mt333x_fw_dump.py", line 147, in <module>
    main()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils\mt333x_fw_dump.py", line 88, in main
    brom.start()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils\mt333x_helpers.py", line 98, in start
    self._ser.write("\xa0")
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyserial-3.3-py3.6.egg\serial\serialwin32.py", line 308, in write
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyserial-3.3-py3.6.egg\serial\serialutil.py", line 63, in to_bytes
TypeError: unicode strings are not supported, please encode to bytes: '\xa0'

I think it maybe because of the version of python and or py.serial as I found a technote on it and have added the .encode() function to all the ser.write commands in mt333x_helpers.py as shown below self._ser.write("\x0a".encode())

The code now gets to the end but I'm still getting errors

C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils>mt333x_fw_dump.py -b 9600 --nmea-baud 9600 com20 output.dat
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils\mt333x_fw_dump.py", line 147, in <module>
    main()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils\mt333x_fw_dump.py", line 88, in main
    brom.start()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\mt333x-fw-utils\mt333x_helpers.py", line 118, in start
    "0x{:02x}".format(ord(c)))
RuntimeError: incorrect response at BOOT_ROM_START_CMD2: 0x5f


I'm going to keep plugging away but if you know of anything obvious I maybe doing wrong any help would be much appreciated, cheers

**Comment by dimhoff** [comment]
I see you are using python 3. This seems to be the issue. I'll take a look if I can fix that. If you don't want to wait for that you can use Python 2.7.13.

**Comment by Gavsv8** [comment]
Yes I just rolled back to Python 2.7.12 with py.serial 3.1.1 and I've managed to dump so I'll continue with this cheers

**Comment by Gavsv8** [comment]
I am trying to change the default update rate from 1 to 10Hz, default enable Galileo and change the default baud and then use this module in INAV flight software which will just read the NMEA strings.

 Is there something that can read the output.dat file data and edit it as a text and hex editor just shows unrecognizable data and I can't get the mt333x_fw_file_info.py to work. The file is attached if you know of a way to find these settings in this data. I'll keep searching and trying things anyway, cheers

[output.zip](https://github.com/dimhoff/mt333x-fw-utils/files/1117683/output.zip)

**Comment by dimhoff** [comment]
Running mt333x_fw_file_info.py on the file works fine for me:

    # mt333x_fw_file_info.py /tmp/output.dat 
    (?) Firmware family: MTKGPS
    Device Type: Gms-g9
    Release Name: AXN
    Release Version: 3.20
    build number: 8033
    
    (?)Firmware size: 450036
    Serial port string: Serial Port0
    
    Baud Rate: 9600
    NMEA Coordinate Precision: 4 digits
    Update Rate: 1
    Sentence rates:
     - GGA: 1
     - GLL: 0
     - ???: 0
     - GSV: 5
     - GSA: 1
     - VTG: 1
     - RMC: 1
     - GLL(2): 0
     - ZDA: 0
    
    GPS Datum: WGS 84
    Nav. Threshold: 0.00
    
    3d-fix LED:
     - no fix: 2.0, 1/2
     - fix: 0.5, OFF
    
    LOCUS settings:
     -  type: Full-Stop
     -  mode: Fix Only, Interval
     -  record content: Timestamp, Validity, Latitude, Longitude, Height, Checksum
     -  interval: 15
     -  distance: 0
     -  speed: 0

Customizing firmwares is not supported by me. GlobalTop has a service to do this. Also enabling Gallileo is not a config option afaik. but requires a whole different firmware.

**Comment by Gavsv8** [comment]
Okay I have it now. I was going to try and work out how the decoding for this info command works and then see if its possible to edit the output.dat file to optimize the default settings. Gallileo can be turned on with the MT3333 using the minigps type tools but all these options are reset after power down.  I moved onto the mt333x_fw_update.py command but it looks like I need the download agent file which I'm assuming is the file that the MTK flash tool uses similar to AXN1.51_2776_3329_384.1151100.5_v19.bin but for the MT3333  V3.2. This is where I'm going to struggle to get this. I contacted global top support to see what can be done so I'll update this if I can make anymore progress as it would be great to be able to modify the default settings as some hosts do not utilize the mediatek commands and only read the nmea strings.  A much better update for gps hold in INAV software could be achieved for the mediatek gps. Thanks again for the great support and for the work done on this so far on this.

**Comment by dimhoff** [comment]
Yes, the agent files are provided with the GlobalTop FlashTools. I updated the README.md with more information.

Note, the files with names similar to AXN1.51_2776_3329_384.1151100.5_v19.bin are firmware files. If you dumped the original firmware from you device you'll won't need one of these. FYI, the firmware you currently are running is called: AXN3.20_8033_3333_96.1151100.1.bin.

If you find out which bits control Gallileo I'd love to know so I can update mt333x_fw_file_info.py.

**Comment by Gavsv8** [comment]
GlobalTop have been taken over by Sierra Wireless and no longer offer the firmware service. This is now no longer an issue for me as code has been developed in INAV to define the MTK GPS and write the commands to increase rates and to optimize the NMEA strings.
